### ISSUE TITLE
[Question] Cannot understand how to generate/use the mapper implementation class generate from the @JsonMapper annotation

### ISSUE THREAD

**Issue by p4535992** [DominoKit/domino-jackson#85]
Here the java code:

```
	@JSONMapper
	public interface AltriMetadatiDTOJsonMapper extends ObjectMapper<Map<String,List<String>>>{}
	
	static AltriMetadatiDTOJsonMapper AltriMetadatiDTOJsonMapperImpl =
		      new XXX_AltriMetadatiDTOJsonMapperImpl();

        String jsonAltriMetadati = AltriMetadatiDTOJsonMapperImpl.write(XXX);
```

I'm getting a compilation error because the class `AltriMetadatiDTOJsonMapper AltriMetadatiDTOJsonMapperImpl` give me the error `error: cannot find symbol`, but form the documentation i cannot understand how i must use the library https://dominokit.com/solutions/domino-jackson/v1/docs/getting-started/define-mappers

when and how i generate the XXXMapperImpl ?

**Comment by niloc132** [comment]
Can you share a full example that shows this - a simple project with just the domino-jackson dependencies, this interface, and the full build log with its error?

**Comment by p4535992** [comment]
I'll try to find the time to replicate the issue on a stand alone project, but is not possibile to set up a interface like i'm currently doing with the old GWTJackson project ?

`public static interface AltriMetadatiDTOMapper extends com.github.nmorel.gwtjackson.client.ObjectMapper<Map<String,List<MetadatoDTOGWT>>> {}` ?

**Comment by p4535992** [comment]
Nothing i try everything the gwt compilation (GWT 2.9.0, GXT 4.1.0, Domino Jackson 1.0.1) go well, but it don't seem to create any xxxMapperImpl class like tell here https://dominokit.com/solutions/domino-jackson/v1/docs/getting-started/define-mappers

I'm trying to use the interface solution so i create this class:

```
// public static interface AltriMetadatiDTOMapper extends com.github.nmorel.gwtjackson.client.ObjectMapper<Map<String,List<MetadatoDTOGWT>>> {
@org.dominokit.jackson.annotation.JSONMapper 
public interface AltriMetadatiDTOMapper extends org.dominokit.jackson.ObjectMapper<Map<String,List<MetadatoDTOGWT>>> {
	
}
```
MetadatoDTOGWT is a simple object with setter and getter.

There is some trick to explicitily generate the xxxMapperImpl class some junit test perhaps ?

**Comment by vegegoku** [comment]
First of all you should not use `GWT.create` with domino-jackson, the classes should be generated using an annotation processor instead of a gwt generator, so first step for you is to confirm that the domino-jackson annotation processor is actually running and generates the implementations. check the target/build folder or whatever based on how you setup your project and what build tool you are using to fins the generated classes, and make sure those generated classes are also included in the project classpath.

If those can be confirmed then you should be able to use the mappers without a problem.

also adding more info to this issue can help, what build tool your are using? how are you setting up your project? how are you adding domino-jackson dependencies?..etc

**Comment by p4535992** [comment]
Yea i noticed there is no rebind mechanism....
For some reason i think, the @JsonMapper annotation do not triggers a annotation processor. 
I cannot find any  generated classes under  'target/generated-sources/annotaions' right ?
i'm try to understand why something so simple on the documentation is not working on my enviroment...

**Comment by vegegoku** [comment]
As I said sharing more about your build and you configure things might help.

**Comment by p4535992** [comment]
Just to avoid any issue with the project. I'll close the ticket . If i'll find out the problem i will share my solution.
